project:
  type: website
  output-dir: posts

website:
  navbar:
    background: light
    search: true
    left:
      - text: "BK Advisors Blog"
        href: https://bk-advisors.github.io/
    right:
      - icon: github
        href: https://github.com/bk-advisors
        
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "./assets/bka_simple.png" />

format:
  html:
    theme: cosmo
    css: blog.css
    toc: true
    code-copy: false
    code-overflow: wrap

execute:
  freeze: auto
